### PR TITLE
[TASK] Adapt to breaking core hook getFlexFormDSClass

### PR DESCRIPTION
**Pull request by lolli42**
Catch up with core version 8.5 by implementing the former
"getFlexFormDSClass" hook as a combination of two smaller
hooks.

Related: #78581

### CODE REVIEW

**Comment by lolli42** [comment]
Don't merge before https://review.typo3.org/#/c/48212/ is merged to the core.

**Comment by einpraegsam** [comment]
Thx Lolli

**Comment by lolli42** [comment]
Mentioned that patch in the core patch as example now:
https://review.typo3.org/#/c/48212/32/typo3/sysext/core/Documentation/Changelog/master/Breaking-78581-HookGetFlexFormDSClassNoLongerCalled.rst

**Comment by lolli42** [comment]
the patch to core master is merged, this one should be ready for review now.

**Comment by einpraegsam** [comment]
Merged into develop branch. Ready for upcoming release.

**Pull request closed without merging**
