### PR TITLE
#182: add ajax submit complete event

### LINKED ISSUE #182: Feature Request: Add AJAX submit complete event
When submitting a powermail form via AJAX, there is currently no way to be notified when the form submission is completed.

We are currently using a workaround like this:

```
function initAjaxSubmitComplete($form) {

        // find or create fake progress bar container
        var fakeProgressBarContainer;
        fakeProgressBarContainer = $form.get(0).querySelector('.fake_progressbar_container');
        if (!fakeProgressBarContainer) {
            fakeProgressBarContainer = document.createElement('div');
            fakeProgressBarContainer.className = 'fake_progressbar_container powermail_fieldwrap_submit';
            $bkwForm.append(fakeProgressBarContainer);
        }

        // create fake progress bar div
        var fakeProgressBar = document.createElement('div');
        fakeProgressBar.className = 'powermail_progressbar';

        // add fake progress bar
        fakeProgressBarContainer.appendChild(fakeProgressBar);
        var statusObject = {
            observer: null
        };
        statusObject.observer = new MutationObserver(ajaxSubmitComplete.bind(this, $form.get('data-powermail-form'), statusObject));
        statusObject.observer.observe(fakeProgressBarContainer, {
            childList: true
        });
    }

    function ajaxSubmitComplete(formUid, statusObject) {
        console.log('ajax submit completed');
        var $form = $('*[data-powermail-form="' + formUid + '"]:first');
        statusObject.observer.disconnect();
        this.initAjaxSubmitComplete($form);
    }
```

It would be nice to be able to register to an event instead.

### PR DESCRIPTION
**Pull request by macjohnny**
Fixes #182

### CODE REVIEW

**Comment by macjohnny** [comment]
@einpraegsam could you have a look at this PR?

**Comment by macjohnny** [comment]
@einpraegsam could you please have a look at this PR?

**Comment by einpraegsam** [comment]
Yes, of course as soon as I have some spare time for it

**Comment by einpraegsam** [comment]
Thx for your work

**Pull request merged**
