### PR TITLE
[PR] backend module list view memory usage fix

### PR DESCRIPTION
**Pull request by cieslix**
Fix big memory consumption on the backend module list view, by reducing iteration to just unique Forms Uids.

In our TYPO3 we have almost 30k unique mails from one Form and memory was reduced from ~720MB to ~12MB.

### CODE REVIEW

**Comment by tmotyl** [comment]
+1

**Comment by einpraegsam** [comment]
The class PreparedStatement will be removed in T3 9. If we want to spend some time in improvement, we should also look into the future. What is your opinion?

**Comment by tmotyl** [comment]
hmm, you're right. PreparedStatement is deprecated in v8 (doctrine should be used from this moment) and removed in v9.
So in order to be v7.6 -> v9 compatible, we should rewrite the query to not use prepared statement, but just a raw statement. 
@einpraegsam do you agree?

**Comment by einpraegsam** [comment]
Yes, agreed :)

**Comment by tmotyl** [comment]
updated

**Comment by einpraegsam** [comment]
Thx for your work. Will check this asap.

**Pull request merged**
