### PR TITLE
[FEATURE] Allow manipulation of message object while using the sendTe…

### PR DESCRIPTION
**Pull request by magicHatOfTYPO3**
…mplateEmailBeforeSend Signal/Slot.

### CODE REVIEW

**Comment by magicHatOfTYPO3** [comment]
this commit allows the manipulation of the $message object before sending it via the named Signal/Slot. I use this to attach a dynamically generated file to the message object, but that's not the end of all possibilities.

**Comment by einpraegsam** [comment]
Hi Magic,

the first argument is an object. In my eyes it shouldn't be needed to pass an object as reference because it's an unique object. Am I wrong?
Did you test manipulation with the current code?

Alex

**Comment by magicHatOfTYPO3** [comment]
Hi Alex,

Sorry for the late answer. Yes I tried it with your code of course. Yes, $message is an object, and I may use it in the Slot to send an email - but the code after the signal will then send another email without the manipulation (in my case without the attachment). With my code in this pull request the Slot is allowed to change the $message object and return it to the power mail code, so the loc right after the signal sends the one and only email (WITH an attachment in my case), which is fine. :)

Of course, the Slot may manipulate anything in the $message object, which makes it very flexible.

**Comment by magicHatOfTYPO3** [comment]
Alex, I apologize. You're right; I cross-checked it on another system where my slot runs smoothly without any patch on the power mail core. So we can close this merge request.

**Comment by einpraegsam** [comment]
Thx for your final feedback :)

**Pull request closed without merging**
